fail_fast = true

[[repos]]
repo = "builtin"
hooks = [
      { id = "trailing-whitespace" },
      { id = "mixed-line-ending" },
      { id = "check-toml" },
      { id = "check-yaml" },
      { id = "check-json" },
      { id = "end-of-file-fixer" },
]

[[repos]]
repo = "local"
hooks = [
    {
        id = "cargo-fmt",
        name = "cargo fmt",
        entry = "cargo fmt --",
        language = "system",
        types = ["rust"],
        pass_filenames = false # This makes it a lot faster
    },

    {
        id = "cargo-clippy",
        name = "cargo clippy",
        language = "system",
        types = ["rust"],
        pass_filenames = false,
        entry = "cargo clippy --all-targets --all-features -- -D warnings"
    },

    {
        id = "cargo-doc",
        name = "cargo doc",
        language = "system",
        types = ["rust"],
        pass_filenames = false,
        entry = "cargo doc --no-deps"

    }
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.44.0"
hooks = [ { id = "typos" } ]
