use std::{convert, sync::Arc};

use itertools::Itertools;
use rootcause::Report;
use stringcase::Caser;

use crate::intermediate::{DataType, Definition, DefinitionRegistry, IntEnum, Json, StringEnum};

#[derive(Debug, Clone, Default)]
pub struct CxxSourceCode {
    filename: String,
    content: String,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum GenerationError {
    #[error("whatever")]
    Whatever,

    #[error("type definition `{name}` not found")]
    TypeNotFound {
        name: String,
        queried_from: Arc<Definition>,
    },
}

pub fn generate_glaze(
    registry: &DefinitionRegistry,
) -> Result<Vec<CxxSourceCode>, Report<GenerationError>> {
    let generated_sources: Result<Vec<CxxSourceCode>, Report<GenerationError>> = registry
        .definitions
        .values()
        .map(|def| match **def {
            Definition::Json(ref json) => generate_json_cxx(registry, json),
            Definition::Struct(ref json) => generate_json_cxx(registry, json),
            Definition::IntEnum(ref int_enum) => generate_int_enum_cxx(registry, int_enum),
            Definition::StringEnum(ref string_enum) => generate_str_enum_cxx(registry, string_enum),
        })
        .collect();

    generated_sources
}

fn generate_json_cxx(
    registry: &DefinitionRegistry,
    json: &Json,
) -> Result<CxxSourceCode, Report<GenerationError>> {
    fn convert_datatype(datatype: &DataType, registry: &DefinitionRegistry) -> String {
        match datatype {
            DataType::I32 { .. } => String::from("int"),

            DataType::U32 { .. } => String::from("unsigned int"),

            DataType::I64 { .. } => String::from("long"),

            DataType::U64 { .. } => String::from("unsigned long"),

            DataType::F32 { .. } => String::from("float"),

            DataType::F64 => String::from("double"),

            DataType::Bool { .. } => String::from("bool"),

            DataType::String => String::from("std::string"),

            DataType::Datetime => String::from("std::chrono::idk???"),

            DataType::DatetimeUnix => String::from("std::chrono::idk_unix???"),

            DataType::Map { key, value } => {
                let key = convert_datatype(key, registry);
                let value = convert_datatype(value, registry);

                format!("std::hashmap<{key}, {value}>")
            }

            DataType::StringArray {
                inner_type: _,
                separator: _,
            } => String::from("std::string"),

            DataType::Array { inner_type } => {
                let inner = convert_datatype(inner_type, registry);

                format!("std::vector<{inner}>")
            }

            DataType::SingleElementArray { inner_type } => {
                let inner = convert_datatype(inner_type, registry);

                format!("std::array<{inner}, 1>")
            }

            DataType::Definition(weak) => match weak.upgrade() {
                Some(definition) => definition.name().clone(),
                None => panic!("Expired entry in registry cache for type {datatype:#?}"),
            },

            DataType::Unknown(other) => match registry.find(other) {
                Some(definition) => definition.name().clone(),
                None => panic!("Could not find definition {other}"),
            },
        }
    }

    let filename = format!("{}.h", json.name);

    let fields = json
        .fields
        .values()
        .map(|field| {
            let datatype = convert_datatype(&field.type_, registry);
            let name = field.name.to_snake_case();

            format!("{datatype} {name};")
        })
        .join("\n");

    let struct_name = json.name.to_pascal_case();

    let content = format!(
        r#"#pragma once
    // File auto-generated by `packet-generator`

    struct {struct_name} {{
        {fields}
    }};"#,
    );

    Ok(CxxSourceCode { filename, content })
}

fn generate_int_enum_cxx(
    _registry: &DefinitionRegistry,
    int_enum: &IntEnum,
) -> Result<CxxSourceCode, Report<GenerationError>> {
    let filename = format!("{}.h", int_enum.name.to_pascal_case());
    let start = int_enum.start;

    let sorted_variants: Vec<_> = int_enum
        .variants
        .values()
        .sorted_unstable_by_key(|a| a.index)
        .collect();

    let mut variants_iter = sorted_variants.iter();

    let first_variant = variants_iter
        .next()
        .map(|variant| {
            let name = variant.name.to_pascal_case();

            let start = variant.value.unwrap_or(start);

            format!("{name} = {start},\n")
        })
        .unwrap_or_default();

    let variants_str = variants_iter
        .map(|variant| {
            let name = variant.name.to_pascal_case();
            let maybe_val = variant.value.map(|v| format!("= {v}")).unwrap_or_default();

            format!("{name} {maybe_val},")
        })
        .join("\n");

    let content = format!(
        r#"#pragma once

// This file is auto-generated by `packet-generator` from a KDL specification.

enum class {} {{
    {first_variant}
    {variants_str}
}};"#,
        int_enum.name.to_pascal_case(),
    );

    Ok(CxxSourceCode { filename, content })
}

fn generate_str_enum_cxx(
    _registry: &DefinitionRegistry,
    str_enum: &StringEnum,
) -> Result<CxxSourceCode, Report<GenerationError>> {
    let filename = format!("{}.h", str_enum.name.to_pascal_case());

    let variants: Vec<_> = str_enum
        .variants
        .values()
        .map(|variant| variant.name.to_pascal_case())
        .collect();

    let variants_str = variants.join(", \n");

    let content = format!(
        r#"#pragma once
// This file is auto-generated by `packet-generator` from a KDL specification.

enum class {} {{
    {variants_str}
}};"#,
        str_enum.name.to_pascal_case(),
    );

    Ok(CxxSourceCode { filename, content })
}
